# Generated by Django 4.2 on 2023-04-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tile',
            new_name='title',
        ),
    ]
