name: Generate requirements.txt

on:
  pull_request:
    branches:
      - master  # o la rama principal de tu proyecto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3  # Reemplaza "3.x" con la versión de Python que estás utilizando

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install project dependencies
        run: poetry install

      - name: Generate requirements.txt
        run: poetry export --output requirements.txt --without-hashes

      
      - name: Fetch latest changes
        run: git fetch origin

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt
          git commit -m "Update requirements.txt" || echo "No changes to commit"

      - name: Print PR Branch Name
        run: |
          echo "PR Branch: ${{ github.head_ref }}"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
